#!/bin/bash
# systemd-cryptsetup-generator(8) and crypto modules.
# /etc/cryptsetup.initramfs is included as etc/crypttab if it exists.
build() {
	run_build_hook dm

	add_module dm-{crypt,integrity}
	add_all_modules /crypto/

	add <<-!
	# cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
	i libgcc_s.so.1

	L /usr/lib/systemd/{
		systemd-cryptsetup
		system-generators/systemd-cryptsetup-generator
	}

	L /usr/bin/systemd-tty-ask-password-agent
	L /usr/sbin/mkswap

	?fr /etc/crypttab.initramfs etc/crypttab
	!
}
