#!/bin/bash
_ls() {
	local -a files=(${@/%//\*})
	files=("${files[@]/\*/' '}")
	printf '%s\n' ${files[@]##*/}
}

_mkinitcpio() {
	local opt_short opt_long cur prev

	opt_short=(A a M b z n c d F f h H o k K L r N p R s S v V g X)
	opt_long=(
		add addhooks
		archive
		automods
		base64
		compress
		concurrent
		config
		debug
		firmware
		force
		help
		hookhelp
		hooks
		kernel
		kmod
		listhooks
		moduleroot
		nogen
		path
		rootfs
		save
		skiphooks
		verbose
		version
		write
	)

	_get_comp_words_by_ref cur prev

	case $prev in
	-r|--moduleroot|-R|--rootfs|-p|--path|-F|--firmware)
		_filedir -d; return ;;
	-k|--kernel)
		COMPREPLY=($(compgen -W "$(_ls {/usr,}/lib/modules)" -- "$cur")); return ;;
	-A|--add|--addhooks|-H|--hookhelp|-S|--skiphooks|-o|--hooks)
		COMPREPLY=($(compgen -W "$(_ls /{etc,lib,usr/lib}/mkinitcpio/install/)" -- "$cur")); return ;;
	esac

	case $cur in
	-*)
		COMPREPLY=($(compgen -W "${opt_short[*]/#/-} ${opt_long[*]/#/--}" -- "$cur")) ;;
	*)
		_filedir ;;
	esac
}

complete -F _mkinitcpio mkinitcpio
