#!/bin/bash
build() {
	run_build_hook dm
	map add_module dm-{mod,snapshot,mirror,cache,cache-smq,thin-pool}
	add_udev_rule 11-dm-lvm.rules 69-dm-lvm-metad.rules
	add_systemd_unit lvm2-pvscan@.service lvm2-lvmetad.service
}

help() { cat <<!
lvm
!
}
