#!/bin/bash
build() {
	local -a units

	busybox --list | awk '/fsck/{next} {print "l busybox usr/bin/"$1}' | add
	add 'L /usr/sbin/busybox usr/bin/busybox'

	add_udev_rule \
		50-udev-default.rules \
		60-persistent-storage.rules \
		64-btrfs.rules \
		80-drivers.rules \
		99-systemd.rules

	units=(
		debug-shell.service

		kmod-static-nodes.service
		systemd-fsck@.service
		systemd-hibernate-resume@.service
		systemd-journald-audit.socket
		systemd-journald-dev-log.socket
		systemd-journald.service
		systemd-modules-load.service
		systemd-tmpfiles-setup-dev.service
		systemd-udev-trigger.service
		systemd-udevd-control.socket
		systemd-udevd-kernel.socket
		systemd-udevd.service
		systemd-volatile-root.service

		initrd-cleanup.service
		initrd-fs.target
		initrd-parse-etc.service
		initrd-root-device.target
		initrd-root-fs.target
		initrd-switch-root.service
		initrd-switch-root.target
		initrd-udevadm-cleanup-db.service
		initrd.target

		emergency.target
		local-fs-pre.target
		local-fs.target
		paths.target
		reboot.target
		rescue.target
		slices.target
		sockets.target
		swap.target
		timers.target
	)
	add_systemd_unit "${units[@]}"

	add_systemd_drop_in systemd-udevd.service resolve-names <<-!
	[Service]
	ExecStart=
	ExecStart=/usr/lib/systemd/systemd-udevd --resolve-names=never
	!

	add <<-!
	f $PWD/{break,sysroot}-generator usr/lib/systemd/system-generators 0755
	!
}

help() { cat <<!
This will install a basic systemd setup in your initramfs, and is meant to
replace the 'init', 'usr', 'udev' and 'resume' hooks. Other hooks with runtime
components will need to be ported, and will not work as intended. You also may
wish to still include the 'base' hook (before this hook) to ensure that a
rescue shell exists on your initramfs.
!
}
