#!/bin/bash
# $ cd github.com/systemd/systemd; ninja -C build
# $ mkinitcpio -o systemd-git -X systemd=$PWD
build() {
	run_build_hook busybox
	add "f $PWD/../../../install/systemd/{break,sysroot}-generator usr/lib/systemd/system-generators 0755"
}
