#!/bin/bash
# Perform auto-detection of kernel modules via sysfs to reduce the included
# kernel modules to only those needed for booting. Be sure to verify the
# included modules are correct and none are missing.
build() {
	local p fstype

	[[ $KERNELVERSION == none ]] && return

	add_if_avail() {
		# treat this as an alias, since ext3 might be aliased to ext4. also, as
		# of linux 3.9, we can find any filesystem by the alias "fs-$name"
		# rather than having to guess at the corresponding module name.
		fstypes+=("$1")
		fs_autodetect_failed=0
		add_autodetect < <(modprobe -qRa {fs-,}"$1")
	}

	auto_modules || return 1

	for p in "${_optrootfs:-/}" "$_optrootfs/usr"; do
		if ! fstype=$(findmnt -uno fstype -T $p); then
			continue
		fi

		case "$fstype" in
		tmpfs) continue ;;
		*) add_if_avail "$fstype" ;;
		esac
	done

	(( fs_autodetect_failed )) && error 'failed to detect root filesystem'

	add_autodetect < <(
		awk '{gsub(/raid[456]/, "raid456"); print}' /sys/class/block/md*/md/level 2>/dev/null
	)

	if (( ${#_autodetect_cache[*]} )); then
		debug 'caching %d modules' "${#_autodetect_cache[*]}"
	fi
}
