#!/bin/bash
# Modules for block devices using NVMe, SATA, PATA, SCSI, FireWire, USB or MMC.
build() {
	local filter

	add_module sd_mod? sr_mod? usb_storage? mmc_block? firewire-sbp2? virtio_blk?

	# pata, sata, scsi, nvme
	for filter in 'scsi/.*ata' '/(block|scsi|fusion|nvme)/' 'ata/[ps]ata_' \
		'ata/(ahci|pdc_adma|ata_piix|ata_generic)'; do
		add_checked_modules "$filter"
	done

	# usb
	add_checked_modules -f '(_cs|sl811_hcd|isp116x_hcd)' '/usb/host'
	add_checked_modules '/drivers/usb/storage/'

	# firewire
	add_checked_modules '/drivers/firewire/'

	# mmc
	add_checked_modules '/(drivers/mmc|tifm_)'

	# virtio
	add_checked_modules 'virtio'
}
