#!/bin/bash
# fsck(8) and filesystem specific helpers.
# fsck.mode= can be used on the kernel command line to control behaviour.
#  "force" unconditionally performs a full filesystem check.
#  "skip" skips all filesystem checks.
# 
# Additional parameters are understood by systemd, see systemd-fsck@.service(8).
build() {
	local f

	add <<-!
	c etc/fstab
	l ../proc/self/mounts etc/mtab

	?fr /etc/e2fsck.conf
	!

	(( fs_autodetect_failed )) && add <<-!
	gL /usr/sbin/fsck.*
	?L /usr/sbin/xfs_repair
	?L /usr/(s|)bin/btrfs
	!

	for f in "${fstypes[@]}"; do
		case "$f" in
		btrfs) add 'L /usr/(s|)bin/btrfs' ;;
		xfs) add 'L /usr/sbin/xfs_repair' ;;
		esac

		if [[ ! -f "$_optrootfs/usr/sbin/fsck.$f" ]]; then
			warning "missing fsck helper: %s" "$f"
			continue
		fi
		add_binary "/usr/sbin/fsck.$f"
	done

	add_binary "/usr/sbin/fsck"
}
