#!/bin/bash
build() {
	add_checked_modules -f 'dm-' 'drivers/md/*'
	add <<-!
	L /usr/sbin/mdadm usr/bin/mdadm

	fr /usr/lib/udev/rules.d/{
		63-md-raid-arrays.rules
		64-md-raid-assembly.rules
	}

	gr /usr/lib/udev/rules.d/65-md-incremental.rules -
	gr /etc/mdadm.conf -
	!
}

help() { cat <<!
mdraid modules and mdadm.
!
}
