#!/bin/bash
build() {
	add_checked_modules -f 'dm-' 'drivers/md/*'
	add 'gr /etc/mdadm.conf -'
	add_udev_rule \
		63-md-raid-arrays.rules \
		64-md-raid-assembly.rules \
		65-md-incremental.rules
}

help() { cat <<!
mdraid modules and mdadm.
!
}
