#!/bin/bash
build() {
	map add_module 'phram' 'mtdblock'

	add <<-!
	f /usr/lib/initcpio/udev/01-memdisk.rules usr/lib/udev/rules.d/01-memdisk.rules
	L /usr/bin/memdiskfind
	!

	add_runscript
}

help() { cat <<!
This hook detects a virtual disk created by the memdisk tool
(http://syslinux.zytor.com/wiki/index.php/MEMDISK).

It requires memdiskfind from syslinux 4.00 or newer.
!
}
