#!/bin/bash
build() {
	add 'L /usr/lib/systemd/systemd-shutdown shutdown'
	if type -P kexec > /dev/null; then
		add_binary kexec
	fi
}

help() { cat <<!
This hook adds systemd-shutdown to the initramfs. This is only
if the image is extracted to /run/initramfs before shutdown.
!
}
