#!/bin/bash
build() {
	add <<-!
	L /usr/bin/{cp,lsblk,findmnt,umount}
	f /usr/lib/initcpio/shutdown shutdown 0755
	!
	add_runscript
}

help() { cat <<!
This hook copies the contents of the initramfs into /run/initramfs for reuse
on shutdown. This is needed when you have /usr mounted on a separate partition.
!
}
