#!/bin/bash
build() {
	add <<-!
	L /usr/lib/systemd/systemd-udevd
	L /usr/bin/{udevadm,systemd-tmpfiles}
	L /usr/lib/udev/{ata,scsi}_id

	fr /usr/lib/udev/rules.d/{
		50-udev-default.rules
		60-persistent-storage.rules
		64-btrfs.rules
		80-drivers.rules
	}
	!
	add_runscript
}

help() { cat <<!
This hook adds the udev daemon to the initramfs, allowing for dynamic loading
of modules and reliable detection of the root device via tags (e.g. UUID or
LABEL). Do not remove this hook unless you are using the systemd hook, or you
know what you're doing.
!
}
