#!/bin/bash
build() {
	add 'L /usr/bin/findmnt'
	add_runscript
}

help() { cat <<!
This provides a support for mounting /usr via a late running hook. No
configuration is needed, as the mount options will be pulled directly from the
fstab on the real root device.
!
}
