#!/bin/bash
# vconsole.conf(5), keymaps and font.
add_keymap_file() {
	local f c inc

	find "$_optrootfs"/usr/@(share|lib)/kbd/keymaps/ \
		-type f -regex ".*/$1\(\.inc\)?\(\.gz\|\.bz2\)?" \
	| while read -r f; do
		add "fr ${f##$_optrootfs}"

		case "$f" in
		*.gz) c=gzip ;;
		*.bz2) c=bzip2 ;;
		esac

		${c:-cat} ${c:+-cd} "$f" | awk -F'"' '/^include/ {print $2}' \
			| while read -r inc; do add_keymap_file "$inc"; done
	done
}

add_consolefont_file() {
	local f
	for f in "$_optrootfs"/usr/@(share|lib)/kbd/consolefonts/"$1".@(fnt|psf?(u))?(.gz); do
		[[ -f $f ]] && add "fr ${f##$_optrootfs}"
	done
}

build() {
	local f vc="$_optrootfs/etc/vconsole.conf"

	add_udev_rule 90-vconsole.rules
	add 'L /usr/bin/{loadkeys,setfont}'

	[[ -s "$vc" ]] || return 0
	add 'fr /etc/vconsole.conf'

	awk -F= '
	$1 ~ /^KEYMAP(|_TOGGLE)/ {print $2".map"}
	$1 == "FONT" {print $2}
	' "$vc" | while read -r f; do
		case "$f" in
		*.map) add_keymap_file "$f" ;;
		*) add_consolefont_file "$f" ;;
		esac
	done
}
