#!/bin/bash
build() {
	run_build_hook busybox

	add_udev_rule \
		50-udev-default.rules \
		60-persistent-storage.rules \
		64-btrfs.rules \
		80-drivers.rules

	add <<-!
	c etc/initrd-release

	d {sys,dev,proc,tmp,run,sysroot}
	l usr/{sbin,bin,lib} /
	l bin usr/sbin

	f $PWD/init{,_functions} / 0755

	L /usr/sbin/{blkid,switch_root}
	L /usr/bin/{u,}mount

	L /usr/bin/kmod
	l kmod usr/bin/{dep,ins,rm,ls}mod
	l kmod usr/bin/mod{probe,info}

	L /usr/lib/systemd/systemd-{udevd,modules-load}
	L /usr/bin/{udevadm,systemd-tmpfiles}
	!
}

help() { echo 'mkinitcpio /init, see mkinitcpio.init(5).'; }
